version: "3"
services:
  postges:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  
  postgres-backupper:
    image: guestros/postgres-s3-backup:latest
    build: .
    container_name: postgres-backupper
    environment:
      - PSQL_HOST=postgres
      - PSQL_PORT=5432
      - S3_BUCKET=postgres-backup
      - S3_PATH=
      - S3_REGION=us-east-1
      - S3_ENDPOINT=https://s3.amazonaws.com
    # rest is set in env file (secret). copy .env.example to .env and fill in the blanks
    env_file:
      - .env